name: auth        # name of the service

targetPort: 8080  # port the container exposes

max_memory: 0.25G # maximum memory to be allocated to the service
max_cpu: 0.25     # max cpu to be allocated to the service
min_memory: 0.1G  # minimum amount of memory to run the service
min_cpu: 0.1      # min CPU to run the service

api_proto: "http" # http or https

auth0:
  domain: "todo-rhs.auth0.com"
  client_id: "WWYXwp7UlXKKcOnRri1V9qmtU2FNLIdq"
  api_audience: "https://todo.example.org"
